name: C++ CI (macOS)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: make unit
      run: |
        echo "#Unit Tests" >> $GITHUB_STEP_SUMMARY
        make -s unit | tee -a $GITHUB_STEP_SUMMARY
    - name: make test
      run: |
        echo "#Integration Tests" >> $GITHUB_STEP_SUMMARY
        make -s test | tee -a $GITHUB_STEP_SUMMARY
