name: C++ CI (Ubuntu)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make linux
      run: make linux
    - name: make unit
      run: make unit
    - name: make test
      run: make test
