name: Tests (Ubuntu)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: pip install
      run: |
        python3 -m pip install --upgrade pip
        pip3 install --upgrade setuptools
        pip3 install --upgrade wheel
        pip3 install -r tests/requirements.txt
    - name: make
      run: make
    - name: make unit
      run: |
        # What is good emoji for unit tests?
        # https://emojipedia.org/search/?q=unit+test
        # :microscope: :test_tube: :alembic: :gear: :gear:
        echo "# Unit Tests :test_tube:" >> $GITHUB_STEP_SUMMARY
        set -o pipefail
        make -s unit | tee -a $GITHUB_STEP_SUMMARY
    - name: make test
      run: |
        echo "# Integration Tests :scientist:" >> $GITHUB_STEP_SUMMARY
        set -o pipefail
        make -s test | tee -a $GITHUB_STEP_SUMMARY
